Consider the below code to answer further questions:

In [2]:
import numpy as np

In [3]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list_[0])

str

In [6]:
array_list.dtype

dtype('<U1')

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for element in list_:
    print(element)

1
2
3
4
5


In [9]:
for element in array_list:
    print(element)

1
2
3
4
5


Q3. Considering the following changes in the variable, array_list:

In [13]:
array_list1 = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
for element in list_:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
for element in array_list:
    print(type(array_list1))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Consider the below code to answer further questions:

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [16]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
num_list

[[1, 2, 3], [4, 5, 6]]

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [18]:
num_array.shape

(2, 3)

In [19]:
num_array.dtype

dtype('int64')

In [22]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
import numpy as np

In [24]:
zeros_array = np.zeros((3,3))

In [26]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [27]:
identity_matrix = np.identity(5)

In [28]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])